Test3

diff --git a/.github/workflows/terraform-appy.yml b/.github/workflows/terraform-appy.yml
--- a/.github/workflows/terraform-appy.yml
+++ b/.github/workflows/terraform-appy.yml
@@ -3,8 +3,11 @@ name: Terraform Apply
 on:
   workflow_dispatch:
     inputs:
-      artifact_id:
-        description: "Artifact ID of the tfplan artifact"
+      account_number:
+        description: "AWS Account Number"
+        required: true
+      branch_name:
+        description: "Branch Name to Apply the Plan"
         required: true
 
 permissions:
@@ -29,24 +32,41 @@ jobs:
       - name: Configure AWS credentials via OIDC
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Github_Role_Demo
+          role-to-assume: arn:aws:iam::${{ inputs.account_number }}:role/Github_Role_Demo
           aws-region: ${{ secrets.AWS_REGION }}
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
 
+      - name: Fetch Artifact ID for Branch
+        id: fetch_artifact
+        run: |
+          branch_name="${{ inputs.branch_name }}"
+          echo "Searching for artifact for branch: $branch_name"
+
+          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
+
+          artifact_id=$(echo "$response" | jq -r --arg branch "tfplan-$branch_name" '.artifacts[] | select(.name == $branch) | .id' | head -n 1)
+
+          if [ -z "$artifact_id" ]; then
+            echo "Error: No artifact found for branch $branch_name"
+            exit 1
+          fi
+
+          echo "artifact_id=$artifact_id" >> $GITHUB_ENV
+
       - name: Verify Artifact
         run: |
-          echo "Artifact ID: ${{ inputs.artifact_id }}"
+          echo "Verifying artifact with ID: ${{ env.artifact_id }}"
           curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ inputs.artifact_id }}"
+               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.artifact_id }}"
 
       - name: Download Plan Artifact
         run: |
           echo "Downloading artifact..."
           curl -L -o tfplan.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ inputs.artifact_id }}/zip"
-          ls -l
+               "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.artifact_id }}/zip"
           unzip tfplan.zip
           ls -l
 
