Test3

diff --git a/.github/workflows/terraform-appy.yml b/.github/workflows/terraform-appy.yml
--- a/.github/workflows/terraform-appy.yml
+++ b/.github/workflows/terraform-appy.yml
@@ -42,12 +42,14 @@ jobs:
         id: fetch_artifact
         run: |
           branch_name="${{ inputs.branch_name }}"
-          echo "Searching for artifact for branch: $branch_name"
+          artifact_name="tfplan-$branch_name"
+
+          echo "Searching for artifact named: $artifact_name"
 
           response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
 
-          artifact_id=$(echo "$response" | jq -r --arg branch "tfplan-$branch_name" '.artifacts[] | select(.name == $branch) | .id' | head -n 1)
+          artifact_id=$(echo "$response" | jq -r --arg name "$artifact_name" '.artifacts[] | select(.name == $name) | .id' | head -n 1)
 
           if [ -z "$artifact_id" ]; then
             echo "Error: No artifact found for branch $branch_name"
@@ -67,7 +69,8 @@ jobs:
           echo "Downloading artifact..."
           curl -L -o tfplan.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.artifact_id }}/zip"
-          unzip tfplan.zip
+
+          unzip -o tfplan.zip || (echo "Failed to unzip tfplan.zip" && exit 1)
           ls -l
 
       - name: Terraform Init
